### ISSUE TITLE
A channel that shares info with other pages

### ISSUE THREAD

**Issue by johnhoysa** [Pageworks/craft-manytomany#17]
I am using the Many to Many plugin and wondering if the below is possible.

I have a channel called Model ID. Model ID is then related to two other sections, Memory and SSD. I want to be able to link entries from Memory to entries in SSD via the Many To Many Field within Model ID.

Below is a picture, edited, to show the field layout and the information I have within the Model ID entry. The information within the entry is what I need to pull in to my Memory and SSD section but can not figure it out.

I feel like I am missing something very simple that might not be in the read me document for the plugin.

Here is a link to the question [on StackExchange]
(https://craftcms.stackexchange.com/questions/26696/many-to-many-plugin-template-help
![many-to-many](https://user-images.githubusercontent.com/487851/41926984-7bede2b0-7936-11e8-8205-5a70bd654519.jpg)
)

Thanks for your help!

**Comment by peter-tell** [comment]
Sorry for the slow reply @johnhoysa 

See my answer here:
https://craftcms.stackexchange.com/questions/26696/many-to-many-plugin-template-help/27779#27779

This is more of a Craft Relationship question than an issue with the plugin.

THanks!
